In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers

2024-01-18 09:39:46.736690: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [11]:

df = pd.read_csv('/Users/luryan/Documents/persona_project/spaceship-titanic/data/train.csv')

In [12]:
df

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8594     9174_01      Earth     False  G/1479/S  PSO J318.5-22  54.0  False   
8595     9175_01     Europa     False   B/299/P    55 Cancri e  32.0  False   
8596     9176_01      Earth     False  F/1773/S    TRAPPIST-1e  24.0  False   
8597     9178_01      Earth     False  F/1877/P    TRAPPIST-1e  53.0  False   
8598     9179_01      Earth      True  G/1494/P    TRAPPIST-1e  26.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0             0.0        0.0           0.0     0.0     0.0   
1           109.0        9.0          25.0   549.0    44.0   
2            43.0     3576.0           0.0  6715.0    49.0   
3             0.0     1283.0         371.0  3329.0   193.0   
4           303.0       70.0         151.0   565.0     2.0   
...           ...        ...           ...     ...     ...   
8594         65.0      670.0           0.0   177.0     0.0   
8595          0.0    10073.0           0.0   168.0   337.0   
8596          0.0      537.0           0.0     5.0   197.0   
8597         49.0      584.0           0.0     0.0    70.0   
8598          0.0        0.0           0.0     0.0     0.0   

                    Name  Transported  
0        Maham Ofracculy        False  
1           Juanna Vines         True  
2          Altark Susent        False  
3           Solam Susent        False  
4      Willy Santantines         True  
...                  ...          ...  
8594   Teryla Lunapperts         True  
8595     Sulaton Dectory         True  
8596   Willy Mcneiderson         True  
8597  Ernard Barnoldeney        False  
8598    Paulah Tranciams         True  

[8599 rows x 14 columns]

In [13]:


# passenger_ids = df.loc[X_test.index, 'PassengerId']
# submission_df = pd.DataFrame({'PassengerId': passenger_ids, 'Transported': predictions.flatten().round().astype(int)})
# submission_df.to_csv('/kaggle/working/sample_submission.csv', index=False)

df['Homeplanet_Mars'] = df['HomePlanet'].apply(lambda x: 1 if x == 'Mars' else 0)
df['Homeplanet_Earth'] = df['HomePlanet'].apply(lambda x: 1 if x == 'Earth' else 0)
df['Homeplanet_Europa'] = df['HomePlanet'].apply(lambda x: 1 if x == 'Europa' else 0)

if 'HomePlanet' in df.columns:
    df = df.drop('HomePlanet', axis=1)

df['Cabin_S'] = df['Cabin'].apply(lambda x: 1 if str(x).split('/')[-1] == 'S' else 0)
df['Cabin_P'] = df['Cabin'].apply(lambda x: 1 if str(x).split('/')[-1] == 'P' else 0)
# df['Cabin'].fillna(df['Cabin_S', 'Cabin_P'].dropna().mean(), inplace=True)

if 'Cabin' in df.columns:
    df = df.drop('Cabin', axis=1)
    
drop = ['PassengerId', 'Destination', 'Name']
df = df.drop(drop, axis=1)

df = df.fillna(df.mean())

coluna_alvo = 'Transported'

X = df.drop(coluna_alvo, axis=1)
y = df[coluna_alvo]
# Padronizar os dados
scaler = StandardScaler()
X = scaler.fit_transform(X)
# X_test = scaler.fit_transform(X_test)

# Dividir os dados em conjunto de treino e teste
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)




In [14]:
X

array([[-0.75570844,  0.70898832, -0.15601523, ...,  1.75753253,
        -0.98694416,  1.03347064],
       [-0.75570844, -0.33656332, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       [-0.75570844,  2.03335373,  6.56304058, ...,  1.75753253,
         1.01322855, -0.96761336],
       ...,
       [-0.75570844, -0.33656332, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       [-0.75570844,  1.68483651, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064],
       [ 1.35654828, -0.19715644, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064]])

In [9]:
X_train = X.iloc[:int(4*len(X)/5)]
X_test = X[int(4*len(X)/5):]


AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [8]:
X_train

array([[-0.75570844,  0.70898832, -0.15601523, ...,  1.75753253,
        -0.98694416,  1.03347064],
       [-0.75570844, -0.33656332, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       [-0.75570844,  2.03335373,  6.56304058, ...,  1.75753253,
         1.01322855, -0.96761336],
       ...,
       [-0.75570844, -0.82448742, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       [ 1.35654828,  0.63928488, -0.15601523, ...,  1.75753253,
        -0.98694416,  1.03347064],
       [-0.75570844,  0.3604711 , -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064]])

In [ ]:
y_train = X_train.Transported
y_test = X_test.Transported

In [5]:
X_test

array([[ 1.35654828, -0.61537709, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       [-0.75570844, -0.05774955, -0.15601523, ...,  1.75753253,
        -0.98694416,  1.03347064],
       [-0.75570844,  2.10305717, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       ...,
       [-0.75570844,  0.49987799, -0.15601523, ...,  1.75753253,
         1.01322855, -0.96761336],
       [ 1.35654828,  0.43017455, -0.15601523, ..., -0.56897951,
         1.01322855, -0.96761336],
       [ 1.35654828, -1.80033562, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064]])

In [6]:
# # Padronizar os dados
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.fit_transform(X_test)

In [8]:
modelo = Sequential()
modelo.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
modelo.add(Dropout(0.3))
modelo.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.2), input_dim=100))
modelo.add(Dense(64, activation='relu'))
modelo.add(Dense(1, activation='sigmoid'))

In [9]:
modelo.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error', metrics=['accuracy'])

# Treinar o modelo
modelo.fit(X_train, y_train, epochs=10, batch_size=22, validation_data=(X_test, y_test))

Epoch 1/10
313/313 [==============================] - 3s 4ms/step - loss: 1.9943 - accuracy: 0.7428 - val_loss: 0.1764 - val_accuracy: 0.7924
Epoch 2/10
313/313 [==============================] - 1s 3ms/step - loss: 0.1639 - accuracy: 0.7777 - val_loss: 0.1469 - val_accuracy: 0.8058
Epoch 3/10
313/313 [==============================] - 1s 3ms/step - loss: 0.1574 - accuracy: 0.7862 - val_loss: 0.1508 - val_accuracy: 0.8006
Epoch 4/10
313/313 [==============================] - 1s 3ms/step - loss: 0.1554 - accuracy: 0.7833 - val_loss: 0.1425 - val_accuracy: 0.8134
Epoch 5/10
313/313 [==============================] - 1s 3ms/step - loss: 0.1518 - accuracy: 0.7910 - val_loss: 0.1449 - val_accuracy: 0.8087
Epoch 6/10
313/313 [==============================] - 1s 3ms/step - loss: 0.1507 - accuracy: 0.7917 - val_loss: 0.1406 - val_accuracy: 0.8151
Epoch 7/10
313/313 [==============================] - 1s 3ms/step - loss: 0.1496 - accuracy: 0.7944 - val_loss: 0.1455 - val_accuracy: 0.8052
Epoch 

In [10]:
predictions = modelo.predict(X_test)

_, acuracia = modelo.evaluate(X_test, y_test)
print(f'Acurácia do modelo: {acuracia}')

print(f'Length of index: {len(df.index)}')
print(f'Length of predictions: {len(predictions)}')

# Create the DataFrame with 'PassengerId' and 'Transported' columns


54/54 [==============================] - 0s 2ms/step - loss: 0.1379 - accuracy: 0.8140
Acurácia do modelo: 0.8139534592628479
Length of index: 8599
Length of predictions: 1720


In [11]:
X_train

array([[ 1.35654828, -0.61537709, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064],
       [ 1.35654828, -0.12745299,  6.56304058, ...,  1.75753253,
        -0.98694416,  1.03347064],
       [ 1.35654828, -0.26685988, -0.15601523, ...,  1.75753253,
         1.01322855, -0.96761336],
       ...,
       [-0.75570844, -0.33656332, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064],
       [ 1.35654828,  1.26661586, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064],
       [-0.75570844,  0.08165733, -0.15601523, ..., -0.56897951,
        -0.98694416,  1.03347064]])

In [12]:
final = pd.DataFrame({'PassengerId': X_test.index, 'Transported': predictions.flatten() > 0.5})

# Save the DataFrame to a CSV file
final.to_csv('/Users/luryan/Documents/persona_project/spaceship-titanic/outputssubmission.csv', index=False)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
# _, acuracia = modelo.evaluate(X_test, y_test)
# modelo.save('/kaggle/input/spaceship-titanic/sample_submission.csv')
# print(f'Acurácia do modelo: {acuracia}')